#pragma once
typedef DWORD(__stdcall *TD2Common11084)(Room *ptRoom, DWORD zero);
extern TD2Common11084 D2Common11084;;
typedef DWORD(__stdcall *TD2GetLevelID)(Room *ptRoom);
extern TD2GetLevelID D2GetLevelID;;
typedef Room *(__stdcall *TD2GetDropRoom)(Room *ptRoom, Position *, Position *, DWORD, DWORD, DWORD, DWORD);
extern TD2GetDropRoom D2GetDropRoom;;
typedef Unit *(__stdcall *TD2Common10242)(Inventory *ptInventory, Unit *ptItem, DWORD bIsClient);
extern TD2Common10242 D2Common10242;;
typedef Unit *(__stdcall *TD2CanPutItemInInv)(Inventory *ptInventory, Unit *ptItem, DWORD p3, DWORD zero, Unit *ptUnit, const char *file, DWORD line);
extern TD2CanPutItemInInv D2CanPutItemInInv;;
typedef Unit *(__stdcall *TD2InvRemoveItem)(Inventory *ptInventory, Unit *ptItem);
extern TD2InvRemoveItem D2InvRemoveItem;;
typedef DWORD(__stdcall *TD2InvAddItem)(Inventory *ptInventory, Unit *ptItem, DWORD posX, DWORD posY, DWORD vValueC, DWORD bIsClient, BYTE page);
extern TD2InvAddItem D2InvAddItem;;
typedef DWORD(__stdcall *TD2Common10250)(const char *file, DWORD line, Inventory *ptInventory, DWORD posX, DWORD posY, DWORD vValueC, DWORD bIsClient, BYTE page);
extern TD2Common10250 D2Common10250;;
typedef DWORD(__stdcall *TD2Common10273)(Inventory *ptInventory, void *unknown);
extern TD2Common10273 D2Common10273;;
typedef Unit *(__stdcall *TD2InventoryGetFirstItem)(Inventory *ptInventory);
extern TD2InventoryGetFirstItem D2InventoryGetFirstItem;;
typedef Unit *(__stdcall *TD2UnitGetNextItem)(Unit *ptItem);
extern TD2UnitGetNextItem D2UnitGetNextItem;;
typedef Unit *(__stdcall *TD2GetRealItem)(Unit *ptUnit);
extern TD2GetRealItem D2GetRealItem;;
typedef DWORD(__stdcall *TD2GetPosX)(Unit *ptUnit);
extern TD2GetPosX D2GetPosX;;
typedef DWORD(__stdcall *TD2GetPosY)(Unit *ptUnit);
extern TD2GetPosY D2GetPosY;;
typedef void(__stdcall *TD2GetPosition)(Unit *ptUnit, Position *pos);
extern TD2GetPosition D2GetPosition;;
typedef DWORD(__stdcall *TD2GetMaxGoldBank)(Unit *ptUnit);
extern TD2GetMaxGoldBank D2GetMaxGoldBank;;
typedef Room *(__stdcall *TD2GetRoom)(Unit *ptUnit);
extern TD2GetRoom D2GetRoom;;
typedef PlayerData *(__stdcall *TD2InitPlayerData)(Unit *ptChar);
extern TD2InitPlayerData D2InitPlayerData;;
typedef PlayerData *(__stdcall *TD2GetPlayerData)(Unit *ptChar);
extern TD2GetPlayerData D2GetPlayerData;;
typedef DWORD(__stdcall *TD2GetDefence)(Unit *ptChar);
extern TD2GetDefence D2GetDefence;;
typedef DWORD(__stdcall *TD2GetChanceToBlock)(Unit *ptChar, DWORD isLODGame);
extern TD2GetChanceToBlock D2GetChanceToBlock;;
typedef DWORD(__stdcall *TD2GetMaxGold)(Unit *ptUnit);
extern TD2GetMaxGold D2GetMaxGold;;
typedef DWORD(__stdcall *TD2Common10572)(Unit *ptObject, DWORD value);
extern TD2Common10572 D2Common10572;;
typedef BYTE(__stdcall *TD2GetObjectFlags)(Unit *ptObject);
extern TD2GetObjectFlags D2GetObjectFlags;;
typedef void(__stdcall *TD2SetObjectFlags)(Unit *ptObject, BYTE flags);
extern TD2SetObjectFlags D2SetObjectFlags;;
typedef DWORD(__stdcall *TD2isInState)(Unit *ptChar, DWORD isLODGame);
extern TD2isInState D2isInState;;
typedef void(__stdcall *TD2AddPlayerStat)(Unit *ptChar, DWORD statID, int amount, DWORD index);
extern TD2AddPlayerStat D2AddPlayerStat;;
typedef int(__stdcall *TD2GetPlayerStat)(Unit *ptChar, DWORD statID, DWORD index);
extern TD2GetPlayerStat D2GetPlayerStat;;
typedef int(__stdcall *TD2GetPlayerBaseStat)(Unit *ptChar, DWORD statID, DWORD index);
extern TD2GetPlayerBaseStat D2GetPlayerBaseStat;;
typedef DWORD(__stdcall *TD2haveDefenceBonus)(Unit *ptChar);
extern TD2haveDefenceBonus D2haveDefenceBonus;;
typedef DWORD(__stdcall *TD2haveFireResBonus)(Unit *ptChar);
extern TD2haveFireResBonus D2haveFireResBonus;;
typedef DWORD(__stdcall *TD2haveColdResBonus)(Unit *ptChar);
extern TD2haveColdResBonus D2haveColdResBonus;;
typedef DWORD(__stdcall *TD2haveLightResBonus)(Unit *ptChar);
extern TD2haveLightResBonus D2haveLightResBonus;;
typedef DWORD(__stdcall *TD2havePoisonResBonus)(Unit *ptChar);
extern TD2havePoisonResBonus D2havePoisonResBonus;;
typedef DWORD(__stdcall *TD2haveDefenceMalus)(Unit *ptChar);
extern TD2haveDefenceMalus D2haveDefenceMalus;;
typedef DWORD(__stdcall *TD2haveFireResMalus)(Unit *ptChar);
extern TD2haveFireResMalus D2haveFireResMalus;;
typedef DWORD(__stdcall *TD2haveColdResMalus)(Unit *ptChar);
extern TD2haveColdResMalus D2haveColdResMalus;;
typedef DWORD(__stdcall *TD2haveLightResMalus)(Unit *ptChar);
extern TD2haveLightResMalus D2haveLightResMalus;;
typedef DWORD(__stdcall *TD2havePoisonResMalus)(Unit *ptChar);
extern TD2havePoisonResMalus D2havePoisonResMalus;;
typedef void *(__stdcall *TD2CompileTxtFile)(DWORD unused, const char *filename, BINField *ptFields, DWORD *ptRecordCount, DWORD recordLength);
extern TD2CompileTxtFile D2CompileTxtFile;;
typedef ItemsBIN *(__stdcall *TD2GetItemsBIN)(DWORD itemID);
extern TD2GetItemsBIN D2GetItemsBIN;;
typedef GemsBIN *(__stdcall *TD2GetGemsBIN)(DWORD gemID);
extern TD2GetGemsBIN D2GetGemsBIN;;
typedef CubeMainBIN *(__stdcall *TD2GetCubeMainBIN)(DWORD cubemainID);
extern TD2GetCubeMainBIN D2GetCubeMainBIN;;
typedef int(__stdcall *TD2GetNbCubeMainBIN)();
extern TD2GetNbCubeMainBIN D2GetNbCubeMainBIN;;
typedef DWORD(__stdcall *TD2GetNextLevelXP)(DWORD classID, DWORD level);
extern TD2GetNextLevelXP D2GetNextLevelXP;;
typedef DWORD(__stdcall *TD2GetMaxLevel)(DWORD classID);
extern TD2GetMaxLevel D2GetMaxLevel;;
typedef DifficultyLevelsBIN *(__stdcall *TD2GetDifficultyLevelsBIN)(DWORD difficultyLevel);
extern TD2GetDifficultyLevelsBIN D2GetDifficultyLevelsBIN;;
typedef DWORD(__stdcall *TD2GetItemQuality)(Unit *ptItem);
extern TD2GetItemQuality D2GetItemQuality;;
typedef DWORD(__stdcall *TD2TestFlags)(Unit *ptUnit, DWORD flags, DWORD line, const char *file);
extern TD2TestFlags D2TestFlags;;
typedef DWORD(__stdcall *TD2GetItemLevel)(Unit *ptItem);
extern TD2GetItemLevel D2GetItemLevel;;
typedef BYTE(__stdcall *TD2ItemGetPage)(Unit *ptUnit);
extern TD2ItemGetPage D2ItemGetPage;;
typedef void(__stdcall *TD2ItemSetPage)(Unit *ptItem, BYTE page);
extern TD2ItemSetPage D2ItemSetPage;;
typedef DWORD(__stdcall *TD2CheckItemType)(Unit *ptItem, DWORD itype);
extern TD2CheckItemType D2CheckItemType;;
typedef int(__stdcall *TD2GetUniqueID)(Unit *ptItem);
extern TD2GetUniqueID D2GetUniqueID;;
typedef void(__stdcall *TD2SetAnim)(Unit *ptUnit, int anim);
extern TD2SetAnim D2SetAnim;;
typedef int *(__stdcall *TD2GetNbRunesBIN)();
extern TD2GetNbRunesBIN D2GetNbRunesBIN;;
typedef RunesBIN *(__stdcall *TD2GetRunesBIN)(int runesID);
extern TD2GetRunesBIN D2GetRunesBIN;;
typedef DWORD(__stdcall *TD2SaveItem)(Unit *ptItem, saveBitField *data, DWORD startSize, DWORD p4, DWORD p5, DWORD p6);
extern TD2SaveItem D2SaveItem;;
typedef void(__stdcall *TD2SetSkillBaseLevel)(Unit *ptChar, DWORD skillID, DWORD slvl, DWORD bRemove, char *, DWORD);
extern TD2SetSkillBaseLevel D2SetSkillBaseLevel;;
typedef DWORD(__stdcall *TD2GetSkillLevel)(Unit *ptChar, SkillData *ptSkill, DWORD includingBonus);
extern TD2GetSkillLevel D2GetSkillLevel;;
typedef DWORD(__stdcall *TD2GetSkillCost)(Unit *ptChar, int skpoints, DWORD skillID, DWORD curSkillLevel);
extern TD2GetSkillCost D2GetSkillCost;;
typedef void(__fastcall *TD2SetNbPlayers)(DWORD nbPlayers);
extern TD2SetNbPlayers D2SetNbPlayers;;
typedef DWORD(__stdcall *TD2SendToServer)(DWORD size, DWORD one, void *data);
extern TD2SendToServer D2SendToServer;;
typedef DWORD(__stdcall *TD2SendToClient)(DWORD zero, DWORD clientID, void *data, DWORD size);
extern TD2SendToClient D2SendToClient;;
typedef void(__stdcall *TD2FogAssertOld)(const char *ptMessage, DWORD eip, DWORD line);
extern TD2FogAssertOld D2FogAssertOld;;
typedef void(__fastcall *TD2FogAssert)(const char *ptMessage, DWORD eip, DWORD line);
extern TD2FogAssert D2FogAssert;;
typedef void *(__fastcall *TD2FogMemAlloc)(DWORD dwMemSize, LPCSTR lpszErrFile, DWORD ErrLine, DWORD Zero);
extern TD2FogMemAlloc D2FogMemAlloc;;
typedef void *(__fastcall *TD2FogMemDeAlloc)(void *ptMemLoc, LPCSTR lpszErrFile, DWORD ErrLine, DWORD Zero);
extern TD2FogMemDeAlloc D2FogMemDeAlloc;;
typedef void *(__fastcall *TD2AllocMem)(DWORD, DWORD dwMemSize, LPCSTR lpszErrFile, DWORD ErrLine, DWORD Zero);
extern TD2AllocMem D2AllocMem;;
typedef void *(__fastcall *TD2FreeMem)(DWORD, void *ptMemLoc, LPCSTR lpszErrFile, DWORD ErrLine, DWORD Zero);
extern TD2FreeMem D2FreeMem;;
typedef DWORD(__fastcall *TD2MPQOpenFile)(char *ptPath, void **buf);
extern TD2MPQOpenFile D2MPQOpenFile;;
typedef DWORD(__fastcall *TD2MPQCloseFile)(void *mpqfile);
extern TD2MPQCloseFile D2MPQCloseFile;;
typedef DWORD(__fastcall *TD2MPQReadFile)(void *mpqfile, BYTE *buffer, DWORD nbToRead, DWORD *nbRead, DWORD, DWORD, DWORD);
extern TD2MPQReadFile D2MPQReadFile;;
typedef DWORD(__fastcall *TD2MPQGetSizeFile)(void *mpqfile, DWORD *toReset);
extern TD2MPQGetSizeFile D2MPQGetSizeFile;;
typedef void(__fastcall *TD2FogGetSavePath)(char *ptPath, DWORD maxsize);
extern TD2FogGetSavePath D2FogGetSavePath;;
typedef void(__fastcall *TD2FogGetInstallPath)(char *ptPath, DWORD maxsize);
extern TD2FogGetInstallPath D2FogGetInstallPath;;
typedef void(__stdcall *TD2Fog10212)(DWORD unknow);
extern TD2Fog10212 D2Fog10212;;
typedef int(__stdcall *TD2GetInstructionPointer)();
extern TD2GetInstructionPointer D2GetInstructionPointer;;
typedef LPWSTR(__fastcall *TD2GetStringFromString)(const char *ptString);
extern TD2GetStringFromString D2GetStringFromString;;
typedef LPWSTR(__fastcall *TD2GetStringFromIndex)(WORD dwIndexNum);
extern TD2GetStringFromIndex D2GetStringFromIndex;;
typedef DWORD(__stdcall *TD2GetLang)();
extern TD2GetLang D2GetLang;;
typedef DWORD(__stdcall *TD2PrintBigNumber)(LPWSTR ptBuf, DWORD number, DWORD size);
extern TD2PrintBigNumber D2PrintBigNumber;;
typedef DWORD(__stdcall *TD2StormMPQOpenFile)(DWORD zero, LPCSTR fileName, DWORD dwSearchScope, void **buffer);
extern TD2StormMPQOpenFile D2StormMPQOpenFile;
typedef void(__stdcall *TD2Storm503)(DWORD, DWORD, DWORD);
extern TD2Storm503 D2Storm503;;
typedef void(__stdcall *TD2FreeWinMessage)(sWinMessage *msg);
extern TD2FreeWinMessage D2FreeWinMessage;;
typedef DWORD(__stdcall *TD2GetResolution)();
extern TD2GetResolution D2GetResolution;;
typedef void(__stdcall *TD2FillArea)(DWORD x1, DWORD y1, DWORD x2, DWORD y2, DWORD color, DWORD transTbl);
extern TD2FillArea D2FillArea;;
typedef void(__stdcall *TD2PrintImage)(sDrawImageInfo *data, DWORD x, DWORD y, DWORD p4, DWORD p5, DWORD p6);
extern TD2PrintImage D2PrintImage;;
typedef void(__fastcall *TD2PrintLineOnTextBox)(void *screen, char *s, DWORD color);
extern TD2PrintLineOnTextBox D2PrintLineOnTextBox;;
typedef void(__fastcall *TD2PrintString)(LPWSTR s, DWORD x, DWORD y, DWORD color, DWORD bfalse);
extern TD2PrintString D2PrintString;;
typedef DWORD(__fastcall *TD2GetPixelLen)(LPWSTR s);
extern TD2GetPixelLen D2GetPixelLen;;
typedef DWORD(__fastcall *TD2SetFont)(DWORD fontID);
extern TD2SetFont D2SetFont;;
typedef void(__fastcall *TD2PrintPopup)(LPWSTR s, DWORD x, DWORD y, DWORD color, DWORD center);
extern TD2PrintPopup D2PrintPopup;;
typedef void(__fastcall *TD2GetPixelRect)(LPWSTR s, DWORD *x, DWORD *y);
extern TD2GetPixelRect D2GetPixelRect;;
typedef DWORD(__fastcall *TD2PrintTextPopup)(LPWSTR s, DWORD x, DWORD y, DWORD uk, DWORD type, DWORD color);
extern TD2PrintTextPopup D2PrintTextPopup;;
typedef void *(__stdcall *TD2CreateTextBox)(DWORD *data);
extern TD2CreateTextBox D2CreateTextBox;;
typedef DWORD(__stdcall *TD2CMP10014)(void *image);
extern TD2CMP10014 D2CMP10014;;
typedef CharStatsBIN *(__fastcall *TD2GetCharStatsBIN)(DWORD charID);
extern TD2GetCharStatsBIN D2GetCharStatsBIN;;
typedef DWORD(__fastcall *TD2CompileCubeInput)(CubeInput *cubeinput, char *s, DWORD p1, DWORD p2);
extern TD2CompileCubeInput D2CompileCubeInput;;
typedef ItemTypesBIN *(__fastcall *TD2GetItemTypesBIN)(DWORD itemTypesId);
extern TD2GetItemTypesBIN D2GetItemTypesBIN;;
typedef ItemStatCostBIN *(__fastcall *TD2GetItemStatCostBIN)(DWORD id);
extern TD2GetItemStatCostBIN D2GetItemStatCostBIN;;
typedef void *(__fastcall *TD2ReadFile)(DWORD mempool, char *filename, DWORD *size, const char *, DWORD);
extern TD2ReadFile D2ReadFile;;
typedef void(__stdcall *TD2LoadSuperuniques)(DWORD mempool);
extern TD2LoadSuperuniques D2LoadSuperuniques;;
typedef InventoryBIN *(__stdcall *TD2GetInventoryBIN)();
extern TD2GetInventoryBIN D2GetInventoryBIN;;
typedef void *(__fastcall *TD2LoadImage)(const char *filename, DWORD filetype);
extern TD2LoadImage D2LoadImage;;
typedef void(__fastcall *TD2FreeImage)(void *image);
extern TD2FreeImage D2FreeImage;;
typedef void(__fastcall *TD2SendMsgToAll)(BYTE *data);
extern TD2SendMsgToAll D2SendMsgToAll;;
typedef DWORD(__stdcall *TD2GetLastMonsterIDFight)();
extern TD2GetLastMonsterIDFight D2GetLastMonsterIDFight;;
typedef void(__stdcall *TD2PrintStatsPage)();
extern TD2PrintStatsPage D2PrintStatsPage;;
typedef DWORD(__fastcall *TD2PrintStat)(Unit *ptItem, Stats *ptStats, DWORD statID, DWORD statIndex, DWORD statValue, LPWSTR lpText);
extern TD2PrintStat D2PrintStat;;
typedef LPWSTR(__fastcall *TD2SetColorPopup)(LPWSTR popupText, DWORD color);
extern TD2SetColorPopup D2SetColorPopup;;
typedef DWORD(__fastcall *TD2PlaySound)(DWORD id, DWORD, DWORD, DWORD, DWORD);
extern TD2PlaySound D2PlaySound;;
typedef void(__fastcall *TD2SendToServerXX)(DWORD size, BYTE *data);
extern TD2SendToServerXX D2SendToServerXX;;
typedef void(__fastcall *TD2TogglePage)(DWORD a, DWORD b, DWORD c);
extern TD2TogglePage D2TogglePage;;
typedef void(__fastcall *TD2ClickOnStashButton)(DWORD x, DWORD y);
extern TD2ClickOnStashButton D2ClickOnStashButton;;
typedef void *(__stdcall *TD2LoadBuySelBtn)();
extern TD2LoadBuySelBtn D2LoadBuySelBtn;;
typedef void *(__fastcall *TD2LoadResImage)(const char *filename);
extern TD2LoadResImage D2LoadResImage;;
typedef void *(__fastcall *TD2FreeResImages)();
extern TD2FreeResImages D2FreeResImages;;
typedef void *(__fastcall *TD2ReceivePacket)(DWORD a, DWORD b);
extern TD2ReceivePacket D2ReceivePacket;;
typedef DWORD(__stdcall *TD2PrintInterface)(void *unknown);
extern TD2PrintInterface D2PrintInterface;;
typedef void(__fastcall *TD2AddClient)(DWORD clientID);
extern TD2AddClient D2AddClient;;
typedef Game *(__stdcall *TD2GetGameByClientID)(DWORD clientID);
extern TD2GetGameByClientID D2GetGameByClientID;;
typedef void(__fastcall *TD2BroadcastFunction)(Game *ptGame, void *fct, void *param);
extern TD2BroadcastFunction D2BroadcastFunction;;
typedef DWORD(__fastcall *TD2SendPacket)(void *ptNetClient, LPVOID pData, DWORD size);
extern TD2SendPacket D2SendPacket;;
typedef void(__fastcall *TD2SetSkillBaseLevelOnClient)(void *ptClient, Unit *ptChar, DWORD skillID, DWORD sLvl, DWORD bRemove);
extern TD2SetSkillBaseLevelOnClient D2SetSkillBaseLevelOnClient;;
typedef DWORD(__stdcall *TD2LinkPortal)(Game *ptGame, Unit *ptObject, DWORD levelEndID, DWORD levelStartID);
extern TD2LinkPortal D2LinkPortal;;
typedef DWORD(__fastcall *TD2VerifIfNotCarry1)(Unit *ptItem, ItemsBIN *itemsData, Unit *ptFirstItem);
extern TD2VerifIfNotCarry1 D2VerifIfNotCarry1;;
typedef Room *(__fastcall *TD2TestPositionInRoom)(Room *ptRoom, DWORD x, DWORD y);
extern TD2TestPositionInRoom D2TestPositionInRoom;;
typedef DWORD(__fastcall *TD2SpawnSuperUnique)(Game *ptGame, Room *ptRoom, DWORD zero1, DWORD x, DWORD y, DWORD minusOne, DWORD superuniqueID, DWORD zero2);
extern TD2SpawnSuperUnique D2SpawnSuperUnique;;
typedef Unit *(__fastcall *TD2SpawnMonster)(DWORD id, DWORD mode, Game *ptGame, Room *ptRoom, DWORD x, DWORD y, DWORD one, DWORD zero);
extern TD2SpawnMonster D2SpawnMonster;;
typedef void(__stdcall *TD2Game235C0)(Game *ptGame, Room *ptRoom);
extern TD2Game235C0 D2Game235C0;;
typedef DWORD(__fastcall *TD2LoadInventory)(Game *ptGame, Unit *pChar, saveBitField *pdata, DWORD p2, DWORD maxSize, DWORD p4, DWORD *ptNbBytesRead);
extern TD2LoadInventory D2LoadInventory;;
typedef Unit *(__fastcall *TD2GameGetObject)(Game *ptGame, DWORD type, DWORD itemNum);
extern TD2GameGetObject D2GameGetObject;;
typedef Unit *(__fastcall *TD2CreateUnit)(DWORD type, DWORD id, DWORD x, DWORD y, Game *ptGame, Room *ptRoom, DWORD uk1, DWORD uk2, DWORD uk3);
extern TD2CreateUnit D2CreateUnit;;
typedef void(__fastcall *TD2OpenPandPortal)(Game *ptGame, Unit *ptChar);
extern TD2OpenPandPortal D2OpenPandPortal;;
typedef void(__fastcall *TD2OpenPandFinalPortal)(Game *ptGame, Unit *ptChar);
extern TD2OpenPandFinalPortal D2OpenPandFinalPortal;;
typedef void(__fastcall *TD2MephAI)(Game *ptGame, Unit *ptMonster, AIParam *args);
extern TD2MephAI D2MephAI;;
typedef void(__fastcall *TD2DiabloAI)(Game *ptGame, Unit *ptMonster, AIParam *args);
extern TD2DiabloAI D2DiabloAI;;
typedef void(__fastcall *TD2BaalAI)(Game *ptGame, Unit *ptMonster, AIParam *args);
extern TD2BaalAI D2BaalAI;;
typedef void(__fastcall *TD2UberBaalAI)(Game *ptGame, Unit *ptMonster, AIParam *args);
extern TD2UberBaalAI D2UberBaalAI;;
typedef void(__fastcall *TD2UberMephAI)(Game *ptGame, Unit *ptMonster, AIParam *args);
extern TD2UberMephAI D2UberMephAI;;
typedef void(__fastcall *TD2UberDiabloAI)(Game *ptGame, Unit *ptMonster, AIParam *args);
extern TD2UberDiabloAI D2UberDiabloAI;;
typedef void(__stdcall *TD2SaveGame)(Game *ptGame);
extern TD2SaveGame D2SaveGame;;
typedef void(__fastcall *TD2MonsterMove)(Game *ptGame, Unit *ptMonster, Unit *target, DWORD two, DWORD x, DWORD y, DWORD one, DWORD zero);
extern TD2MonsterMove D2MonsterMove;;
typedef void(__fastcall *TD2MonsterUseSkill)(Game *ptGame, Unit *ptMonster, DWORD arg, DWORD skill, Unit *target, DWORD x, DWORD y);
extern TD2MonsterUseSkill D2MonsterUseSkill;;
typedef void(__fastcall *TD2SaveSPChar)(Game *ptGame, Unit *ptChar, char *name, DWORD arg, DWORD secondPass);
extern TD2SaveSPChar D2SaveSPChar;;
//ONLY UNTIL 1.10 :
typedef DWORD(__fastcall *TD2isLODGame)();
extern TD2isLODGame D2isLODGame;;
typedef BYTE(__fastcall *TD2GetDifficultyLevel)();
extern TD2GetDifficultyLevel D2GetDifficultyLevel;;
typedef DWORD(__stdcall *TD2GetMouseX)();
extern TD2GetMouseX D2GetMouseX;;
typedef DWORD(__stdcall *TD2GetMouseY)();
extern TD2GetMouseY D2GetMouseY;;
typedef Unit *(__stdcall *TD2GetClientPlayer)();
extern TD2GetClientPlayer D2GetClientPlayer;;
typedef void(__fastcall *TD2CleanStatMouseUp)();
extern TD2CleanStatMouseUp D2CleanStatMouseUp;;
typedef void(__fastcall *TD2SendToServer3)(BYTE type, WORD p);
extern TD2SendToServer3 D2SendToServer3;;
typedef NetClient *(__fastcall *TD2GetClient)(Unit *ptUnit, char *lpszErrFile, DWORD ErrLine);
extern TD2GetClient D2GetClient;;
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////// VARIABLES ////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
extern DWORD *ptResolutionY;;
extern DWORD *ptResolutionX;;
extern DWORD *ptNegWindowStartY;;
extern DWORD *ptWindowStartX;;
extern NetClient **ptClientTable;;
extern DWORD *ptIsLodGame;;
extern BYTE *ptDifficultyLevel;;
extern DWORD *ptMouseY;;
extern DWORD *ptMouseX;;
extern Unit **ptptClientChar;;
extern DWORD *ptInputCommandLen;;
extern WCHAR *ptInputCommand;;
extern DWORD *ptNbStatDesc;;
extern DWORD *ptStatDescTable;;